---
version: 2

run:
  timeout: "5m"

output:
  sort-results: true

linters-settings:
  gosec:
    excludes:
      - "G404"  # Allow the usage of math/rand
  rowserrcheck:
    packages:
      - "github.com/jackc/pgx"

linters:
  enable:
    - "errcheck"
    - "govet"
    - "ineffassign"
    - "staticcheck"
    - "unused"
    - "bodyclose"
    - "gosec"
    - "revive"
    - "rowserrcheck"
    - "errorlint"
    - "gocritic"
    - "unconvert"
    - "wastedassign"
    - "whitespace"
    - "importas"
    - "prealloc"
    - "predeclared"
    - "bidichk"

issues:
  exclude-rules:
    - text: "tx.Rollback()"
      linters:
        - "errcheck"
    # NOTE: temporarily disable deprecation checks for v0.
    - path: "internal/services/"
      linters:
        - "staticcheck"
      text: "SA1019"
    - path: "internal/middleware/consistency/"
      linters:
        - "staticcheck"
      text: "SA1019"
    - path: "pkg/proto/core/v1/core.pb.validate.manual.go"  # Ignore manual definition of metadata map
      linters:
        - "revive"
      text: "ST1003|var-naming"
    # Ignore receiver errors for generic types not understood by the linter.
    - linters:
        - "revive"
      text: 'receiver-naming: receiver name \S+ should be consistent with previous receiver name \S+ for invalid-type'
