---
name: "Lint"
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - "!dependabot/*"
      - "main"
  pull_request:
    branches: ["*"]
  merge_group:
    types:
      - "checks_requested"
env:
  GO_VERSION: "~1.20.4"
jobs:
  go-lint:
    name: "Lint Go"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "authzed/actions/setup-go@main"
        with:
          go-version: "${{ env.GO_VERSION }}"
      - name: "Lint Go"
        run: "go run mage.go lint:go"
      - uses: "chainguard-dev/actions/nodiff@main"
        with:
          path: ""
          fixup-command: "go run mage.go lint:go"

  extra-lint:
    name: "Lint YAML & Markdown"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - name: "Lint Everything Else"
        run: "go run mage.go lint:extra"
      - uses: "chainguard-dev/actions/nodiff@main"
        with:
          path: ""
          fixup-command: "go run mage.go lint:extra"

  codeql:
    name: "Analyze with CodeQL"
    runs-on: "ubuntu-latest-8-cores"
    permissions:
      actions: "read"
      contents: "read"
      security-events: "write"
    strategy:
      fail-fast: false
      matrix:
        language: ["go"]
    steps:
      - uses: "actions/checkout@v3"
      - uses: "authzed/actions/codeql@main"

  trivy:
    name: "Analyze with Trivy"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "aquasecurity/trivy-action@0.9.0"
        with:
          scan-type: "fs"
          ignore-unfixed: true
          format: "sarif"
          output: "trivy-results.sarif"
          severity: "CRITICAL"
      - name: "Upload Trivy scan results to GitHub Security tab"
        uses: "github/codeql-action/upload-sarif@v2"
        with:
          sarif_file: "trivy-results.sarif"
