---
name: "Build & Test"
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "*"
  merge_group:
    types:
      - "checks_requested"
env:
  GO_VERSION: "~1.24.0"
jobs:
  unit:
    name: "Unit Tests"
    runs-on: "depot-ubuntu-24.04"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "authzed/actions/setup-go@main"
        with:
          go-version: "${{ env.GO_VERSION }}"
      - name: "Unit tests"
        run: "go run mage.go test:unit"

  # Build validation
  build:
    name: "Build"
    runs-on: "depot-ubuntu-24.04"
    needs: "unit"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "authzed/actions/setup-go@main"
        with:
          go-version: "${{ env.GO_VERSION }}"
      - name: "Build"
        run: "go build ./..."
      - name: "Vet"
        run: "go vet ./..."
